@baseUrl=http://localhost:3000/api

###
GET {{baseUrl}} HTTP/1.1

###
POST {{baseUrl}}/client/register HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "test"
}

###
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "test"
}

###
POST {{baseUrl}}/auth/logout HTTP/1.1

###
GET {{baseUrl}}/common/hotel-rooms HTTP/1.1

###
GET {{baseUrl}}/common/hotel-rooms/66945bee31a60498b7814af6 HTTP/1.1

###
POST {{baseUrl}}/admin/hotels HTTP/1.1
Content-Type: application/json

{
    "title": "Example hotel {{$randomInt 1 100}}",
    "description": "Example description {{$guid}}"
}

###
GET {{baseUrl}}/admin/hotels?title=3 HTTP/1.1

###
PUT {{baseUrl}}/admin/hotels/66912aeeb3eae5d309465448 HTTP/1.1
Content-Type: application/json

{
    "title": "Edited hotel {{$randomInt 1 100}}",
    "description": "Edited description {{$guid}}"
}

###
POST {{baseUrl}}/admin/hotel-rooms HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Room #{{$randomInt 1 100}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="hotelId"

6693c515d38027c4f6041670
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="alexandra-gorn-JIUjvqe2ZHg-unsplash.jpg"
Content-Type: image/jpeg

< ./assets/alexandra-gorn-JIUjvqe2ZHg-unsplash.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="lotus-design-n-print-WgkA3CSFrjc-unsplash.jpg"
Content-Type: image/jpeg

< ./assets/lotus-design-n-print-WgkA3CSFrjc-unsplash.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
PUT {{baseUrl}}/admin/hotel-rooms/66945bee31a60498b7814af6 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Room #{{$randomInt 1 100}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="hotelId"

6693c515d38027c4f6041670
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"

cabd694aab8e49822712d5cfb1f3531c.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"

cabd694aab8e49822712d5cfb1f3531c.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="alexandra-gorn-JIUjvqe2ZHg-unsplash.jpg"
Content-Type: image/jpeg

< ./assets/alexandra-gorn-JIUjvqe2ZHg-unsplash.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="lotus-design-n-print-WgkA3CSFrjc-unsplash.jpg"
Content-Type: image/jpeg

< ./assets/lotus-design-n-print-WgkA3CSFrjc-unsplash.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
